start cmd /k python send_msgs.py
start cmd /k python send_msgs.py
start cmd /k python send_msgs.py
start cmd /k python send_msgs.py
start cmd /k python send_msgs.py
start cmd /k python send_msgs.py
start cmd /k python send_msgs.py
start cmd /k python send_msgs.py
start cmd /k python send_msgs.py
start cmd /k python send_msgs.py